name: Build CaseBot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain

    - name: Compile Bot
      shell: msys2 {0}
      run: |
        g++ bot.cpp -o casebot.exe -lgdi32 -luser32

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: casebot-executable
        path: casebot.exe
