name: Build CaseBot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile Bot
      run: g++ bot.cpp -o casebot.exe -lgdi32 -luser32

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: casebot-executable
        path: casebot.exe
